### ISSUE TITLE
RPM for latest stable version missing in yum repo

### ISSUE THREAD

**Issue by Aadit-Bhojgi** [redis-stack/redis-stack-rpm#3]
RPM for stable release version tag **v6.2.4** is not available in official Redis yum repository for CentOS 7.
Can anyone tell me what is the procedure to publish this?

[Linux installation link](https://redis.io/docs/stack/get-started/install/linux/#from-the-official-rpm-feed)
Currently only packages upto stable release version **6.2.2_v3-1** are available:

> redis-stack-server.x86_64                                                                 6.2.0_v1-1.rhel7                                                                   Redis
> redis-stack-server.x86_64                                                                 6.2.2_v2-1.rhel7                                                                  Redis
> **redis-stack-server.x86_64                                                                 6.2.2_v3-1.rhel7                                                                  Redis**

**Comment by chayim** [comment]
@ofekshenawa this is the reason I want to move to rpm-s3

**Comment by chayim** [comment]
Hi @Aadit-Bhojgi sorry about this. Found the issue - it's actually how CI triggers + tags here. I pushed new tags, so the latest **stable** version (6.2.4-v4) is now available in the repositories.

We will need to split out and support betas (or rcs), but that's another issue. Mind making sure this works as expected?
