### ISSUE TITLE
RediSearch coordinator module missing in RPM

### ISSUE THREAD

**Issue by Aadit-Bhojgi** [redis-stack/redis-stack-rpm#6]
In the compiled module for`RediSearch v2.4.5` bundled in redis-stack-server RPM (_redis-stack-server-6.2.2_v3-1.rhel7.x86_64_) RSCoordinator module support is missing in the RPM.
Followed [this link](https://redis.io/docs/stack/search/development/#:~:text=with%20CLang%20Sanitizer-,Building%20from%20source,-make%20build%20will) to build RediSearch with Coordinator manually.

shouldn't this module (`/RediSearch/bin/linux-x64-release/coord-oss/module-oss.so`) be shipped in the RPM by default?

**Comment by chayim** [comment]
The co-ordinator is not (currently) designated to part of redis-stack constellation. Please advocate in the redisearch repository, if it out be.
